services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $extension: '@Paustian\WebsiteFeeModule\PaustianWebsiteFeeModule'

  Paustian\WebsiteFeeModule\:
    resource: '../../*'